#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#
#    android-arm32-fix
#
#    ----------------------------------------------------------------------
#    Copyright © 2026       Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.


_android_arm32_fix() {
  local \
    _arch \
    _file \
    _file_name \
    _pkgs
  _arch="$(
    uname \
      -m)"
  _pkgs="$(
    find \
      "${PWD}" \
      -iname \
        "*.pkg.tar.xz" || \
    true)"
  for _file in ${_pkgs}; do \
    echo \
      "file: ${_file}"; \
    _file_name="${_file%*-armv8l.pkg.tar.xz}"
    echo \
      "file: ${_file}"
    if [[ "${_arch}" == "armv8l" ]]; then \
      mv \
        "${_file}" \
        "${_file_name}-arm.pkg.tar.xz" || \
      true
      mv \
        "${_file}.sig" \
        "${_file_name}-arm.pkg.tar.xz.sig" || \
      true
    fi
  done
}

_android_arm32_fix
